# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

env:
  # 👇 Chromatic projectToken, refer to the manage page to obtain it.
  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

on: push

jobs:
  chromatic-deployment: # This job is for deploying to Chromatic and executing VRT on Chromatic.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install && bun run prepare

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true
          zip: true
          buildScriptName: 'storybook:build'
